parameters:
  imageName: ''
  tag: ''
  azAccount: ''
  region: ''
  repo: ''

jobs:
  - job: Build
    displayName: Build & Push Image
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self

      - script: |
          docker build -t ${{ parameters.imageName }}:${{ parameters.tag }} .
        displayName: Build Docker Image

      - script: |
          aws ecr get-login-password --region ${{ parameters.region }} \
          | docker login --username AWS --password-stdin \
          ${{ parameters.awsAccount }}.dkr.ecr.${{ parameters.region }}.amazonaws.com

          docker tag ${{ parameters.imageName }}:${{ parameters.tag }} \
          ${{ parameters.awsAccount }}.dkr.ecr.${{ parameters.region }}.amazonaws.com/${{ parameters.repo }}:${{ parameters.tag }}

          docker push ${{ parameters.awsAccount }}.dkr.ecr.${{ parameters.region }}.amazonaws.com/${{ parameters.repo }}:${{ parameters.tag }}
        displayName: Push to ECR